name: "nms"
backend: "python"
max_batch_size: 8
input [
  {
    name: "candidate_boxes"
    data_type: TYPE_FP32
    dims: [ 1000, 6 ]
  }
]

output [
  {
    name: "BBOXES"
    data_type: TYPE_FP32
    # padding number of bboxes to 300
    dims: [ 300, 6 ]
  }
]



model_warmup [
{
    batch_size: 8
    name: "warmup_requests"
    inputs: {
        key: "candidate_boxes"
        value: {
            random_data: true
            dims: [1000, 6]
            data_type: TYPE_FP32
            }
    }
}
]


parameters: { 
  key: "FORCE_CPU_ONLY_INPUT_TENSORS" 
  value: {string_value:"no"}
  }

